### ISSUE TITLE
Google JWT Error

### ISSUE THREAD

**Issue by ngrkajac** [kyma-project/cloud-manager#382] opened 2024-07-25 16:22 UTC
**Description**
Search logs for `Invalid JWT Signature.`

```
resource.labels.pod_name=~"cloud-manager.*"
"Invalid JWT Signature."
```

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by ravi-shankar-sap** [comment] 2024-07-29 23:32
The issue was triggered by the credential rotations by the SRE team.

The credential rotation resulted in the update of the secret `cloud-manager-env-gcp`. This update was only detected by the GCP Authentication check, while the GCP service API calls were still using the old credentials and failing with 500 error responses.
The issue is fixed now in the following PRs:

- SRE team updated the credential rotation logic to include a rollout restart. [https://github.tools.sap/kyma/management-plane-config/pull/5471](https://github.tools.sap/kyma/management-plane-config/pull/5471) 
- Fixed on the Cloud Manager to update the httpClient with the newly loaded credentials. [https://github.com/kyma-project/cloud-manager/pull/389](https://github.com/kyma-project/cloud-manager/pull/389)

**Closed** 2024-07-30 16:25 UTC
Labels: kind/bug
